// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg1QZVNN4ZD1Bld8z8NqU2-uxuzMPIR_8',
    appId: '1:194435249090:web:3f4ba3f8af7c2d4e751c5b',
    messagingSenderId: '194435249090',
    projectId: 'footduel-93bf6',
    authDomain: 'footduel-93bf6.firebaseapp.com',
    storageBucket: 'footduel-93bf6.firebasestorage.app',
    measurementId: 'G-GZW3Q1H9SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnn4PSXNF-n8WccB4MpsKTp1FQRC-dQug',
    appId: '1:194435249090:android:e872e89ee9b93752751c5b',
    messagingSenderId: '194435249090',
    projectId: 'footduel-93bf6',
    storageBucket: 'footduel-93bf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36tU3UbxaSmuPxP7fKX8TAp9pLCU2QxQ',
    appId: '1:194435249090:ios:220008b3dd1d4258751c5b',
    messagingSenderId: '194435249090',
    projectId: 'footduel-93bf6',
    storageBucket: 'footduel-93bf6.firebasestorage.app',
    iosBundleId: 'com.example.footDuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36tU3UbxaSmuPxP7fKX8TAp9pLCU2QxQ',
    appId: '1:194435249090:ios:220008b3dd1d4258751c5b',
    messagingSenderId: '194435249090',
    projectId: 'footduel-93bf6',
    storageBucket: 'footduel-93bf6.firebasestorage.app',
    iosBundleId: 'com.example.footDuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg1QZVNN4ZD1Bld8z8NqU2-uxuzMPIR_8',
    appId: '1:194435249090:web:93f6097ee59daa91751c5b',
    messagingSenderId: '194435249090',
    projectId: 'footduel-93bf6',
    authDomain: 'footduel-93bf6.firebaseapp.com',
    storageBucket: 'footduel-93bf6.firebasestorage.app',
    measurementId: 'G-3T2ZF5BKRG',
  );
}
